### ISSUE TITLE
curly brackets aren't removed

### ISSUE THREAD

**Issue by nschloe** [mcmtroffaes/latexcodec#36]
The following test fails:
```python
import latexcodec
text_latex = b"{t}est"
assert text_latex.decode("latex") == u"test"
```

**Comment by mcmtroffaes** [comment]
Thanks for the report. However, this behaviour is intentional. See https://github.com/mcmtroffaes/latexcodec/blob/8856843/latexcodec/codec.py#L589 - however I should put this more prominently in the documentation.

If you need to remove brackets, you can use:

```python
text_latex.decode("latex").replace("{", "").replace("}", "")
```

**Comment by mcmtroffaes** [comment]
... also see http://stackoverflow.com/a/19754245/2863746 - this is now mentioned in the docs, so closing.
