### ISSUE TITLE
Unknown encoding "ulatex"

### ISSUE THREAD

**Issue by xuhdev** [mcmtroffaes/latexcodec#37]
I tried the example in the "Get Started":

```python
import codecs
import latexcodec
text_latex = u"\\'el\\`eve"
codecs.decode(text_latex, "ulatex")
```

However, I got the error 

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    codecs.decode(text_latex, "ulatex")
LookupError: unknown encoding: ulatex
```

The result is the same on both Python 2 and 3

**Comment by xuhdev** [comment]
I tested this issue exists only when installed with `pip`... Maybe you missed some files in the pip repository?

**Comment by mcmtroffaes** [comment]
Sorry for the delay in my response - I'm travelling at the moment. It's not yet in any released version - you've probably been looking at the documentation for the development version?

**Comment by xuhdev** [comment]
I see. Thanks!
