### ISSUE TITLE
whitespace handling: strip or not strip?

### ISSUE THREAD

**Issue by xuhdev** [mcmtroffaes/latexcodec#40]
The current decoding function seems strip all spaces in the beginning and end:

```python
import codecs
import latexcodec
text_latex = b" hello world "
print(text_latex)
print(codecs.decode(text_latex, "latex"))
```

However, if `text_latex` is `b"\t hello world "`, the tab is not stripped. I can understand there are good reasons for stripping and not stripping, but this seems to me a non-consistent behavior...

**Comment by mcmtroffaes** [comment]
Yep. That's tex for you. There's a so-called "space eating" mode of the lexer, which eats spaces but not tabs as far as I know. Do you know whether tex treats tab characters exactly as a space characters?

**Comment by xuhdev** [comment]
I don't know, I didn't really find any relevant information on the Internet. Maybe we can just choose to not strip the string?

**Comment by mcmtroffaes** [comment]
See "Tex by Topic", section 2.5, page 32:

https://bitbucket.org/VictorEijkhout/tex-by-topic/src/16b5340c1b9a19ac36165fa6f0d367608d50e995?at=default

I've looked again but it seems that only character code 32 is considered for skipping. However... I did some testing and it looks like current latex implementations also consider tab characters to be spaces. :-/ So yes we should also skip those.

**Comment by mcmtroffaes** [comment]
Tabs and spaces are now treated equally by the lexer, so this should resolve the inconsistent behaviour. Thanks again for reporting!
