### ISSUE TITLE
Skip all unknown unicode characters

### ISSUE THREAD

**Issue by xuhdev** [mcmtroffaes/latexcodec#41]
The following code leads to errors:

```python
import codecs
import latexcodec
text_latex = u"hello wórld 來"
print(text_latex)
print(codecs.encode(text_latex, "ulatex"))
```

    ValueError: 'latex' codec can't encode character '\u4f86' in position 0: don't know how to translate '來' into latex

Maybe we can ignore unknown unicode characters? Actually, I think it might be a good idea to fall back to `utf-8` encoding if an unknown unicode char is encountered.

**Comment by xuhdev** [comment]
Nevermind, I should pass in the `ignore` or `replace` option... Can you make a new release of latexcodec, for the `ulatex` encoding? I've just made a PR for pybtex to make use of this package https://bitbucket.org/pybtex-devs/pybtex/pull-requests/4/using-latexcodec-to-decode-latex-strings/diff

**Comment by mcmtroffaes** [comment]
Sure, I will push a new release in a moment.

**Comment by mcmtroffaes** [comment]
Done.
