### ISSUE TITLE
Percent sign is not decoded

### ISSUE THREAD

**Issue by jgosmann** [mcmtroffaes/latexcodec#48]
`b'\\%'.decode('latex')` gives `u'\\%'`, but should produce `u'%'`.

**Comment by mcmtroffaes** [comment]
Thanks for reporting. I've pushed a fix for this, would you care to test? It's in the feature/fix-percent branch.

**Comment by jgosmann** [comment]
Seems to work for me. :smiley:

**Comment by mcmtroffaes** [comment]
Ok thanks for testing and confirming! I've had to make some changes deep within the lexer to make this work so I appreciate it. I'll make a release later today.

**Comment by mcmtroffaes** [comment]
Just a heads up that 1.0.4 is released, including a fix for this. Let's then tackle the issue with urls in pybtex.
