### ISSUE TITLE
lower case z accents

### ISSUE THREAD

**Issue by AndrewSwann** [mcmtroffaes/latexcodec#51]
Several of the lower case z accents, seem not to be translated, including `\'z`, i.e. z with an accute.

**Comment by mcmtroffaes** [comment]
thanks for reporting; they are in the table but looks like there are some typo's here (capital Z instead of lower case z for some symbols): https://github.com/mcmtroffaes/latexcodec/blob/develop/latexcodec/codec.py#L366 - should be easily fixed

**Comment by mcmtroffaes** [comment]
I've just fixed this issue in the above commit - and sorry for taking such a long time! Any other accents still missing?

**Comment by AndrewSwann** [comment]
Many thanks.  This looks good and I haven't spotted any further such case errors.

**Comment by mcmtroffaes** [comment]
Thanks - I'll release a new version including a fix for this soon.
