### ISSUE TITLE
Possible issue with ampersand and underscore encoding

### ISSUE THREAD

**Issue by Nagasaki45** [mcmtroffaes/latexcodec#54]
Hi!

Tracing down a bug in a [project of mine](https://github.com/Nagasaki45/bibo), that is based on [pybtex](https://pybtex.org/) (that uses `latexcodec`) lead me to think that there might be a problem with encoding of ampersands and underscores in `latexcodec`. The examples bellow are for ampersands but the same apply for underscores.

I have a `.bib` file like this:

```
@ARTICLE{johndoe,
    author = "Doe, John",
    title = "hello \& world",
    year = "2020",
}
```
The problem is that I read the file using pybtex, and then write it back to file, and get:

```
@ARTICLE{johndoe,
    author = "Doe, John",
    title = "hello \\& world",
    year = "2020",
}
```

Notice the extra backslash.

It seems that pybtex doesn't really manipulate the value `"hello \& world"` when it reads the file. But it uses `latexcodec` encoding to write it back to file. Using `latexcodec` directly I get the following:

```
>>> import latexcodec
>>> codecs.encode('hello \\& world', 'ulatex+UTF-8')
'hello \\\\& world'

>>> print(codecs.encode('hello \\& world', 'ulatex+UTF-8'))
hello \\& world
```

I'm not 100% sure that you considered it as a bug, because I don't know the `.bib` specs (if such thing even exists). I also noticed that there is some kind of handling of ampersands in `latexcodec`.

If it is a bug I will be happy to help solving it.

Thanks!

**Comment by mcmtroffaes** [comment]
Apologies for not getting back to you earlier on this. The source is latex, so you need to do 

```
>>> codecs.decode(b"hello \\& world", "latex+utf8")
'hello & world'
```

And conversely:

```
>>> codecs.encode(u"hello & world", "latex+utf8")
b'hello \\& world'
```

I can't comment on what pybtex is doing, but the behaviour of latexcodec seems correct to me in this example. The issue seems to be that you have your encoding/decoding directions the wrong way around.
