### ISSUE TITLE
Missing equivalent UTF-8 for latex value {\'{\i}} (it should be í)

### ISSUE THREAD

**Issue by emiliosalazardonate** [mcmtroffaes/latexcodec#57]
The latex value {\'{\i}} seem not to be translated to í.
This is the text I tried to translate but got a wrong value:
{Mart{\'{\i}}nez-N{\'u}{\~n}ez}   -->  Mart''ınez Núñez (should be Martínez Núñez)

**Comment by mcmtroffaes** [comment]
These accents are quite complicated to get right. If you write it as

```
Mart\\'\\i nez N\\'u\\~nez
```

then the codec should get it right (just tested locally). When in doubt, try this:

```
u'Martínez Núñez'.encode("latex")
```

and if this succeeds, the codec supports all characters, and will also show you how you can write it properly in latex to ensure that the codec can also decode it again.
