### ISSUE TITLE
Scandinavian character å / {\r{a}}

### ISSUE THREAD

**Issue by Tigraan** [mcmtroffaes/latexcodec#59]
In LateX, `Tunest{\r{a}}l` compiles to "Tunestål", but in latexcodec:
```
import latexcodec
s_in = r'Tunest{\r{a}}l'
s_unicode = s_in.encode().decode('latex')
print(s_unicode)  # result: "Tunest{\r {a}}l"
```

Per https://en.wikipedia.org/wiki/%C3%85#On_computers it seems to be a single-Unicode-point character (U+00E5 latin small letter a with ring). Same issue for the capital (U+00C5 latin capital letter a with ring).

My Python (3.5) does not seem to know the Unicode names, but it can use the code points:
```
# print(u'\N{LATIN SMALL LETTER A WITH RING}')  # causes a SyntaxError "unknown Unicode character name"
print('\u00E5')  # works: "å"
```

**Comment by mcmtroffaes** [comment]
Thanks for flagging. The "\aa" and "\AA" notations were already supported for this, but I've added your alternative "\r a" and "\r A" to the decoder now as well.
