### ISSUE TITLE
`\"{\i}` does not get decoded correctly

### ISSUE THREAD

**Issue by davidweichiang** [mcmtroffaes/latexcodec#65]
expected result: `ï`
actual result: `\"{ı}`

This happens because the `\i` is translated before the rule for `\"` can see it.

**Comment by mcmtroffaes** [comment]
See #58 ... I think this is the same issue. Basically, I don't see how this can be fixed without building a fully fledged parser. :-/ This will still work though: ``\"\i``.

**Comment by davidweichiang** [comment]
Oh, sorry for the duplicate. And I apologize that I think this is the second time I did that!

Would it be too ugly to do
```
        self.register(u'\N{LATIN SMALL LETTER I WITH DIAERESIS}', b'\\"ı') # note: dotless i
```
which I think would fix the issue?

**Comment by mcmtroffaes** [comment]
No worries. I'm afraid your solution won't fly. ``ı`` is not a binary character. But more importantly, the buffer is only iterated once. In Python 3:

```python
>>> b'\\"ı'
  File "<stdin>", line 1
SyntaxError: bytes can only contain ASCII literal characters.
```

**Comment by mcmtroffaes** [comment]
I'll close this, as it is (unfortunately) not easy to fix with the current design.
