### ISSUE TITLE
`\. {I}` does not decode correctly

### ISSUE THREAD

**Issue by davidweichiang** [mcmtroffaes/latexcodec#66]
expected result: `İ`
actual result: `\. {I}`

The reason seems to be that `\.` is classified as a `control_symbol_x` rather than a `control_symbol`. The comment in the code says:

```
        # in latex, some control tokens skip following whitespace
        # ('control-word' and 'control-symbol')
        # others do not ('control-symbol-x')
        # XXX TBT says no control symbols skip whitespace (except '\ ')
        # XXX but tests reveal otherwise?
```

But it appears that all control symbols skip following whitespace when they are looking for an argument, as noted in TBT 2.10.4: "When TeX is looking for an undelimited macro argument it will accept the first token (or group) that is not a space."

**Comment by mcmtroffaes** [comment]
Thanks for flagging. I guess that the question is then whether a macro is in play or not... For instance, "\# a" is not the same as "\#a" (presumably because "\#" is not considered a macro). I guess the solution here is simply to add the \. operator to the control symbol class?

**Comment by mcmtroffaes** [comment]
Thanks for flagging. I guess that the question is then whether a macro is in play or not... For instance, "\# a" is not the same as "\#a" (presumably because "\#" is not considered a macro). I guess the solution here is simply to add the \. operator to the control symbol class?

**Comment by mcmtroffaes** [comment]
I think this is fixed now as per the above commit. Please do let me know if it still poses a problem.

**Comment by davidweichiang** [comment]
Yes, thanks, I can’t think of any other cases. (It seems to me that `\!` does not take an argument so shouldn’t be a `control_symbol`, right?)

**Comment by mcmtroffaes** [comment]
Aye, I think that's right.
