### ISSUE TITLE
Lacking documentation of escaping behavior

### ISSUE THREAD

**Issue by tschantzmc** [mcmtroffaes/latexcodec#70]
The project documentation could be improved to make the project goals and the trade-offs made to achieve them more clear.  When backslashes are escaped and treated as characters is complex but undocumented.  Some design rational may make it easier to understand.

I don't believe there to be a canonical way of decoding Latex. For example, the decoder could decode an unescaped underscore and an escaped underscore both as simply an underscore (thereby losing information), or the decoder could try to preserve information about whether the underscore was escaped using some encoding. As far as I can tell, this project has decided to go with the first option, perhaps with readability in mind.

Similarly, choices must be made when encoding into Latex, such as whether to treat an underscore as a character (escaped) or as the directive to do a subscript (unescaped).  The project went with treating it as a character (escaped), perhaps because the input is just plain text after all.

What makes things more confusing, and the need for more documentation on these choices clear, is that the backslash at the start of command names is treated in the opposite manner to the backslash found before an underscore.  That is, it is not dropped when decoding nor escaped when encoding. This inconsistency makes it hard to see a consistent pattern, but perhaps giving the project's goals there is one, or at least documentation could explain which backslashes will be treated in which manner. As seen in issues #17, #48, and #53, this can be subtle.

Below is a script I wrote to help me understand this API's behavior and its output using Version 1.0.7 and Python 3.6.5.

Source:

```python3
#! /usr/bin/env python3

import codecs
import latexcodec


codec = 'ulatex+UTF-8'


def test(string, note=None):
    decoded = codecs.decode(string, codec)
    if note:
        print(note)
    print([string,
           codecs.encode(string, codec),
           decoded,
           codecs.encode(decoded, codec),])
    print()


print("Output format:")
print("optional notes")
print("[input, encoded, decoded, decoded and re-encoded]")
print()

print("\n### Encodes escapes special characters (even those already escaped) since it views its input as plain text (.txt), not code (.tex):\n")
test(r"\#1 Dad!", r"encode escapes # and \; decode prints plain #; decode-encode successfully round trips")
test(r"\newcommand{\test}[1]{testing: #1}", r"encode escapes the #, even when re-encoding")
test(r"\&", r"encode escapes & and \; decode prints plain &; decode-encode successfully round trips")
test(r"&", r"encode escapes the &, even when re-encoding")
test(r"file\_name", r"encode escapes _ and \; decode prints plain _; decode-encode successfully round trips")
test(r"$x_{i} + 2^n$", r"encode escapes the _, even when re-encoding...")
test(r"a_b", r"...outside math mode too...")
test(r"\url{example.com/a_b}", r"...and even in URLs")

print("\n### Inconsistently, however, encode doesn't escape the \ in command names, perhaps because text with ad hoc latex is so common in, e.g., email:\n")
test(r"runs on \LaTeX,", r"encode and decode does nothing but add pointless space")
test(r"including math: \[ \rightarrow \]$", r"encode and decode does nothing")

print("\n### Encode also doesn't escape the \ for diacritics, but decode converts them:\n")
test(r'\"u', r"decode coverts to non-ascii UTF-8 char")
test(r'ü', r"but encode doesn't convert back since we're using ulatex+UTF-8")

print("\n### The behavior gets rather complex:\n")
test(r" \ ", r"encode does nothing; decode converts to space; decode-encode loses the type of space")
test(r"A~B", r"encode replaces ~ with text command for one; decodes it to a non-breaking space in Latin1 (ISO 8859-1), i.e., chr(160)")
test(r"hi % comment", r"encode escapes %; decode strips comments")
test(r"100\% better", r"encode escapes % and \; decode prints plain %; decode-encode successfully round trips")
```

Output:

```
Output format:
optional notes
[input, encoded, decoded, decoded and re-encoded]


### Encodes escapes special characters (even those already escaped) since it views its input as plain text (.txt), not code (.tex):

encode escapes # and \; decode prints plain #; decode-encode successfully round trips
['\\#1 Dad!', '\\\\#1 Dad!', '#1 Dad!', '\\#1 Dad!']

encode escapes the #, even when re-encoding
['\\newcommand{\\test}[1]{testing: #1}', '\\newcommand{\\test}[1]{testing: \\#1}', '\\newcommand {\\test }[1]{testing: #1}', '\\newcommand {\\test }[1]{testing: \\#1}']

encode escapes & and \; decode prints plain &; decode-encode successfully round trips
['\\&', '\\\\&', '&', '\\&']

encode escapes the &, even when re-encoding
['&', '\\&', '&', '\\&']

encode escapes _ and \; decode prints plain _; decode-encode successfully round trips
['file\\_name', 'file\\\\_name', 'file_name', 'file\\_name']

encode escapes the _, even when re-encoding...
['$x_{i} + 2^n$', '$x\\_{i} + 2^n$', '$x_{i} + 2^n$', '$x\\_{i} + 2^n$']

...outside math mode too...
['a_b', 'a\\_b', 'a_b', 'a\\_b']

...and even in URLs
['\\url{example.com/a_b}', '\\url{example.com/a\\_b}', '\\url {example.com/a_b}', '\\url {example.com/a\\_b}']


### Inconsistently, however, encode doesn't escape the \ in command names, perhaps because text with ad hoc latex is so common in, e.g., email:

encode and decode does nothing but add pointless space
['runs on \\LaTeX,', 'runs on \\LaTeX,', 'runs on \\LaTeX ,', 'runs on \\LaTeX ,']

encode and decode does nothing
['including math: \\[ \\rightarrow \\]$', 'including math: \\[ \\rightarrow \\]$', 'including math: \\[ \\rightarrow \\]$', 'including math: \\[ \\rightarrow \\]$']


### Encode also doesn't escape the \ for diacritics, but decode converts them:

decode coverts to non-ascii UTF-8 char
['\\"u', '\\"u', 'ü', 'ü']

but encode doesn't convert back since we're using ulatex+UTF-8
['ü', 'ü', 'ü', 'ü']


### The behavior gets rather complex:

encode does nothing; decode converts to space; decode-encode loses the type of space
[' \\ ', ' \\ ', ' ', ' ']

encode replaces ~ with text command for one; decodes it to a non-breaking space in Latin1 (ISO 8859-1), i.e., chr(160)
['A~B', 'A\\textasciitilde B', 'A\xa0B', 'A\xa0B']

encode escapes %; decode strips comments
['hi % comment', 'hi \\% comment', 'hi ', 'hi ']

encode escapes % and \; decode prints plain %; decode-encode successfully round trips
['100\\% better', '100\\\\% better', '100% better', '100\\% better']
```

**Comment by mcmtroffaes** [comment]
You can find the documentation here:

https://latexcodec.readthedocs.io/en/latest/quickstart.html

Whilst the test you've done is interesting and hopefully helps you to come to a better understanding, it is important to bear in mind that for encoding, the input is a unicode text string, and the output is its LaTeX equivalent. Similarly, for decoding, the input is a LaTeX string, and the output is its unicode equivalent. So, running encode and decode on the same string, as you do in your test, whilst educationally interesting, makes no sense in a practical setting.

Round-trip equivalence is not guaranteed, although an effort is done to keep things reasonable.

The codec does some simple TeX lexing, but no parsing beyond that. In particular it does not understand the full LaTeX syntax. That's a limitation of the implementation, unfortunately (as documented).

The treatment of backslashes in plain text when encoding to LaTeX works by leaving LaTeX commands in plain text alone. In this way, it provides a simple way to propagate LaTeX commands from your plain text, if that's desired. I could see a case for converting backslashes in things that look like LaTeX commands, but that would be a major behavioural change...

**Comment by tschantzmc** [comment]
Thank you for your quick reply.

I agree that the encoding tests weren't using your API in the intended manner.  I ran them since that's how Pybtex uses it, as discussed in issue #54.

Thanks for your description.  I think the reason I was having a hard time understanding the goals of latexcodec is that I think of codecs as working over character sets and Latex is not a character set but rather a programming language for producing documents.  If I understand your description, your goal is to go between the subset of Latex that is character-like and unicode while passing the rest of Latex through unchanged (unlike `detex`, which drops it with spell checking in mind, or `tex2mail`, which attempts to render some of the math in ascii art for email).

If so, I'm still a bit confused by the exact notion of "character-like" you're using.  For example, using my little script, I find that

 - `$\theta$` is converted, but `\texttheta` is not:
```
['$\\theta$', '$\\theta$', 'θ', 'θ']
['\\texttheta', '\\texttheta', '\\texttheta ', '\\texttheta ']
```

 - `\pounds` is converted, but `\yen` is not:
```
['\\pounds', '\\pounds', '£', '£']
['\\yen', '\\yen', '\\yen ', '\\yen ']
['$\\yen$', '$\\yen$', '$\\yen $', '$\\yen $']
['\\textyen', '\\textyen', '\\textyen ', '\\textyen ']
['$\\textyen$', '$\\textyen$', '$\\textyen $', '$\\textyen $']
```
 - `\par` is converted, but `\\` is not:
```
['a\\par b', 'a\\par b', 'a\n\nb', 'a\n\nb']
['a\\\\ b', 'a\\\\ b', 'a\\\\ b', 'a\\\\ b']
```
Maybe this is just because latexcodec is a work in progress, but maybe I'm missing a distinction you're drawing?

**Comment by mcmtroffaes** [comment]
Well, all symbols need to be manually added. \yen and \texttheta have not yet been added (that would be easy to do, actually I've just added them; there's many more Greek letters to be added). There are so many packages with different symbols, so this is always a work in progress.

Concerning \\par and \\, this is a tricky one. The strict way of doing it would be to use the unicode paragraph separator (http://www.fileformat.info/info/unicode/char/2029/index.htm) for \\par, and newlines for \\, but unfortunately the unicode paragraph separator seems to be poorly supported e.g. python appears to completely ignore this character, at least on my system:

```
>>> print(u"a\u2029b")
ab
```

For the time being, \\ is therefore passed through, and \\par is converted back and forth as double newlines, to keep the result close to the LaTeX source. The guiding principle is: don't touch what we cannot convert easily.

**Comment by tschantzmc** [comment]
Given what you wrote, I believe the following is an accurate depiction of latexcodec.  Do you agree?  If so, what do you think of adding it to the docs?

This codec provides a convenient way of going between text written in LaTeX and unicode.  Since it is not a LaTeX compiler, it is more appropriate for short chunks of text, such as a paragraph or the values of a BibTeX entry, than for a full LaTeX document.  In particular, its behavior on the LaTeX commands that do not simply select characters is intended to allow the unicode representation to be understandable by a human reader, but is not canonical and may require hand tuning to produce the desired effect.

The encoding replaces unicode characters outside of the range used as LaTeX input (ascii by default) with a LaTeX command that selects the character.  More technically, the unicode code point is replaced by a LaTeX command that selects a glyph that reasonably represents the code point.  Some unicode characters with special uses in LaTeX are escaped or replaced by commands.  For example, 

- the unicode code point `165`, which can be produced in Python3 with `chr(165)`, `chr(0xA5)`, `u"\u00A5"`,`u"\N{YEN SIGN}"`, and `"¥"`, is replaced with the LaTeX command `\yen`;

- the unicode code point `252`, produced in Python3 with `chr(252)`, `u"\u00FC"`, `u"\N{LATIN SMALL LETTER U WITH DIAERESIS}"`, or `"ü"`, is replaced by the LaTeX command `\"u`;

- the unicode code point `160`, that is, `u"\u00A0"` and `u"\N{NO-BREAK SPACE}"`, is replaced by the LaTeX command `~`;

- the unicode code point `126`, that is, `u"~"`, is replaced by the LaTeX command `\textasciitilde`; and

- the unicode code point `37`, that is, `u"%"`, is replaced by the LaTeX escaped character `\%`.

Note that the LaTeX commands can be a control sequence, a control sequence and argument value, or an active character.

The decoding replaces LaTeX commands that select characters with the unicode for the character they are selecting.  For example,

- the LaTeX control sequence `\yen` is replaced by the unicode code point `165` (i.e., `u"¥"`);

- the LaTeX control sequence and argument value `\"u` is replaced by the code point `252` (i.e., `u"ü"`);
 
- the LaTeX active character `~` is replaced by `160` (i.e., `u"\N{NO-BREAK SPACE}"`); and

- the LaTeX escaped character `\%` is replaced by `37` (i.e., `u"%"`).

Decoding drops commented text.  For example, the LaTeX `hi % bye` is decoded as `u"hi "`.

When decoding, LaTeX commands not directly selecting characters (for example, macros and formatting commands) are pass through unchanged.  The same happens for LaTeX commands that select characters but aren't yet recognized by the codec. (Given the numerous and changing packages providing such LaTeX commands, the codec might never be complete.)  Either case can result in a hybrid unicode string in which some characters are understood as literally the character and others as parts of unexpanded commands.

The encoder is aware of this behavior and sometimes does not encode backslashes (i.e., `u"\\"`) as the LaTeX `\backslash` but instead leaves it intact for denoting the start of unrecognized control sequences.  However, the encoder cannot tell the intent behind some chacters, like `u"#"`, which could be either a literal pound sign or denoting a macro parameter. It assumes the first and escapes them.  For example, the LaTeX `\newcommand{\example}[1]{\"u and #1}` will be decoded as `u'\\newcommand {\\example }[1]{ü and #1}'`, which will be re-encoded as `\newcommand {\example }[1]{\"u and \#1}`.  Note that the re-encoded version escapes the parameter `#1`, changing the macro's definition.

**Comment by mcmtroffaes** [comment]
I do like that, thanks for writing that all up! I've slimmed it down slightly and rephrased a few things, but it's now part of the readme (which is also part of the documentation). Please have a look and see if you're also happy with it:

https://github.com/mcmtroffaes/latexcodec/blob/develop/README.rst

**Comment by tschantzmc** [comment]
Looks good.  Thanks for posting it.
