### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by vstinner** [mcmtroffaes/latexcodec#75]
Python 3.9 changed codecs.lookup(): the encoding name is now normalized before calling search functions. See:
* https://bugs.python.org/issue37751
* https://bugzilla.redhat.com/show_bug.cgi?id=1789613

I propose attached PR to support Python 3.9.

**Comment by vstinner** [comment]
Fixed by commit a30ae2cf061d7369b1aaa8179ddd1b486974fdad. That's enough for my need (Fedora can backport fixes). I close the issue, thanks!

**Comment by mcmtroffaes** [comment]
Splendid. I'll push a new release soon with the fix as well.
