### ISSUE TITLE
decode adds superfluous space

### ISSUE THREAD

**Issue by nschloe** [mcmtroffaes/latexcodec#80]
MWE:
```python
import latexcodec
import codecs

string = "\ch{ABC}"
out = codecs.decode(string, "ulatex")
print(out)  # "\ch {ABC}", should be "\ch{ABC}"
```

**Comment by mcmtroffaes** [comment]
Quoting from the documentation: "Spacing after LaTeX commands is also canonicalized." This is a feature, not a bug. "\ch {H2O2}" will be rendered by LaTeX just as "\ch{H2O2}", because LaTeX enters space eating mode following any command. You may test it yourself:

```latex
\documentclass{article}
\usepackage{chemformula}
\begin{document}
\ch {H2O2}
\end{document}
```

**Comment by nschloe** [comment]
Of course, thanks for looking into this! :+1:

**Comment by mcmtroffaes** [comment]
You're welcome, and thanks for reporting either way. I'm glad I could help clarifying.
