### ISSUE TITLE
can't encode character '\ufffd'

### ISSUE THREAD

**Issue by nschloe** [mcmtroffaes/latexcodec#83]
Like #68.
```python
import codecs
import latexcodec

codecs.encode(u"\ufffd", "ulatex")
```
See nschloe/betterbib#147.

**Comment by mcmtroffaes** [comment]
Thanks for reporting. This is the unicode replacement character: https://www.fileformat.info/info/unicode/char/0fffd/index.htm

Not sure how this should be handled with respect to the LaTeX end. Any suggestions?
