### ISSUE TITLE
UnicodeEncodeError: 'latex' codec can't encode character '\u200b' in position 0: don't know how to translate '\u200b' into latex

### ISSUE THREAD

**Issue by tgy** [mcmtroffaes/latexcodec#92]
This "zero-width space" character also seems to not be parsed by latexcodec

It seems to be linked with ligatures: https://dfarq.homeip.net/u200b-what-it-is-and-why-it-messes-up-your-code-or-data/

**Comment by mcmtroffaes** [comment]
It allows line breaks without hyphenation. The closest translation appears to be ``\hspace{0pt}``. I'll have a look.

**Comment by tgy** [comment]
Your `\hspace{0pt}` translation is in accordance with what some people are saying here https://tex.stackexchange.com/questions/352623/unicode-char-u200b

**Comment by mcmtroffaes** [comment]
Fixed in develop. Thanks again for reporting!
