### ISSUE TITLE
Duplicated `&` character in journal name

### ISSUE THREAD

**Issue by tgy** [mcmtroffaes/latexcodec#94]
When using https://github.com/nschloe/betterbib `betterbib-format` program to format my bibtex entries, internally `latexcodec` is used to encode strings into the `ulatex` codec.

I noticed that whenever my journal name (and I guess any other entry) contains the `&` character, it gets duplicated.

Due to this duplication, the new bibtex file **does not compile anymore** and it was hard for me to understand and debug what was going on in the first place.

I've created a small reproduction of the issue with the following program.

```python
# v / ~ $ cat /tmp/reproduce.py
import codecs

import latexcodec

journal = 'Neuroscience \\& Biobehavioral Reviews'

encoded = codecs.encode(journal, 'ulatex')

print(repr(journal))
print(repr(encoded))
```

```
v / ~ $ python /tmp/reproduce.py
'Neuroscience \\& Biobehavioral Reviews'
'Neuroscience \\\\& Biobehavioral Reviews'
```

Is this expected behaviour?

**Comment by mcmtroffaes** [comment]
Thanks for the report. I can't speak for betterbib, but this test actually looks fine and is expected. You're asking to encode 'Neuroscience \\& Biobehavioral Reviews' to latex. Did you intend to decode instead, to produce utf-8 from an encoded latex string?

**Comment by mcmtroffaes** [comment]
Closing due to lack of response and not 100% this is a bug... (at least the example is expected behaviour on the latexcodec front). If there's still something wrong somewhere with latexcodec itself, please feel free to reopen with further details.
