### ISSUE TITLE
Drop unprintable characters instead of failing

### ISSUE THREAD

**Issue by JensHeinrich** [mcmtroffaes/latexcodec#95]
eg. `\x98` which marks a string beginning

**Comment by mcmtroffaes** [comment]
This is supported by python itself, via the ``errors`` argument: see https://docs.python.org/3/library/codecs.html#error-handlers

For example,

```
b'...'.decode(errors='replace')
b'...'.decode(errors='ignore')
```

and so on.

**Comment by mcmtroffaes** [comment]
Hope that suggestion worked out for you, if not, feel free to reopen with more details of what you tried, what happened, and what you expected instead.
