### ISSUE TITLE
open_text removed from python 3.13

### ISSUE THREAD

**Issue by jamesjer** [mcmtroffaes/latexcodec#98]
Line 102 of latexcodec/codec.py:
```[python]
with pkg_resources.open_text('latexcodec', 'table.txt') as datafile:
```
invokes a method that was deprecated in python 3.9 and has been removed from python 3.13.  See https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for the migration guide.  Replacing that line with the following works for python 3.9 and later:
```[python]
with (pkg_resources.files('latexcodec') / 'table.txt').open('r', encoding='utf-8', errors='strict') as datafile:
```

**Comment by mcmtroffaes** [comment]
This is now fixed in develop. Thank you for reporting!

**Comment by effigies** [comment]
@mcmtroffaes Would it be possible to get this patch released?

**Comment by mcmtroffaes** [comment]
Thanks for the prompt. I've just made a new release.

**Comment by effigies** [comment]
Thanks! I'm now trying to remember what project I was using that led me here...
